global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/alerts.indexlab.yml

scrape_configs:
  - job_name: "deep-spec-harvester"
    metrics_path: /metrics
    static_configs:
      # TODO: point this at your app metrics endpoint.
      - targets: ["host.docker.internal:8787"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
