use_default_settings: true

general:
  instance_name: "Spec Harvester Local Search"

search:
  safe_search: 0
  formats:
    - html
    - json

server:
  base_url: http://127.0.0.1:8080/
  secret_key: "change-this-local-secret"
  limiter: false
  public_instance: false
  image_proxy: false
  method: "GET"
